name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: IT4Change/vuepress-build-and-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: swjtuhub/tangyuanchunqiu
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: export NODE_OPTIONS=--max_old_space_size=4096 && yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://tycq.swjtu.top
